In [73]:
import pandas as pd

In [74]:
#df_league_2023 = pd.read_excel('data/data_league_2023.xlsx')
df_league_2024 = pd.read_excel('data/data_league_2024.xlsx')
df_league_2024['MES'] = df_league_2024['DATA'].apply(lambda x: x.month)
df_league_2024['ANO'] = df_league_2024['DATA'].apply(lambda x: x.year)

#df_league = pd.concat([df_league_2023, df_league_2024])

In [75]:
df_league_2024

,DATA,COMPETIÇÃO,RODADA,PARTIDA,PLAYER,POSIÇÃO,TIME,V,E,D,...,AZUL,VER,PP,GS,DD,DP,FALTA,PTS,MES,ANO
0,2024-01-22,LIGA,1,1,Courtois,GK,PRETO,NaN,NaN,1.0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,-9.0,1,2024
1,2024-01-22,LIGA,1,1,Paulo Rafael,ATA,PRETO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,1,2024
2,2024-01-22,LIGA,1,1,Diego Maradona,MEI,PRETO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,1,2024
3,2024-01-22,LIGA,1,1,Thiago,MEI,PRETO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,1,2024
4,2024-01-22,LIGA,1,1,Pentelho,ATA,PRETO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,2024-03-18,LIGA,8,88,Thiago,MEI,BRANCO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,-4.0,3,2024
1052,2024-03-18,LIGA,8,88,Léo Cardoso,MEI,BRANCO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,3,2024
1053,2024-03-18,LIGA,8,88,Lotta,MEI,BRANCO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,3,2024
1054,2024-03-18,LIGA,8,88,Nino,MEI,BRANCO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,3,2024
1055,2024-03-18,LIGA,8,88,Hazin,ATA,BRANCO,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.0,3,2024

In [76]:
df_rodadas_no_mes = df_league_2024.groupby(['MES','RODADA']).agg({'RODADA':'count'}).rename({'RODADA':'PARTIDAS_JOGADAS'},axis=1).reset_index().drop('PARTIDAS_JOGADAS', axis=1).groupby('MES').agg({'RODADA':'count'}).rename({'RODADA':'TOTAL_RODADAS_MES'},axis=1).reset_index()

In [77]:
df_lista_presenca = df_league_2024.groupby(['PLAYER', 'MES','RODADA']).agg({'RODADA':'count'}).rename({'RODADA':'PARTIDAS_JOGADAS'},axis=1).reset_index().drop('PARTIDAS_JOGADAS', axis=1)

In [78]:
df_lista_presenca = df_lista_presenca.groupby(['PLAYER', 'MES']).agg({'RODADA':'count'}).rename({'RODADA':'PRESENCAS_NO_MES'},axis=1).reset_index()

In [79]:
dff_lista_presenca = pd.merge(df_lista_presenca, df_rodadas_no_mes, how='left', on='MES')
dff_lista_presenca = dff_lista_presenca[['PLAYER', 'MES', 'TOTAL_RODADAS_MES', 'PRESENCAS_NO_MES']]
dff_lista_presenca['FALTAS'] = dff_lista_presenca['TOTAL_RODADAS_MES'] - dff_lista_presenca['PRESENCAS_NO_MES']
dff_lista_presenca['FALTAS_PERC'] = round((dff_lista_presenca['FALTAS'] / dff_lista_presenca['TOTAL_RODADAS_MES'])*100, 2)

In [80]:
dff_lista_presenca.to_excel('lista_faltas.xlsx', index=False)

faltando entender ql mes o cara é mensal e meio que dar um left merge